### ISSUE TITLE
getaddressbalance is not a method in bitcoind

### ISSUE THREAD

**Issue by jasonedison** [ashishbhate/bcsearch#1]
Is there a new way to get the balance from bitcoind?
https://github.com/ashishbhate/bcsearch/blob/master/bcsearch/balances.py#L25

**Comment by seega** [comment]
> Is there a new way to get the balance from bitcoind?
> https://github.com/ashishbhate/bcsearch/blob/master/bcsearch/balances.py#L25

good question, I liked the code, but it’s not working

**Comment by ashishbhate** [comment]
I had this repo configured to not send me notifications, so I missed these comments.

That method works because this code requires bitcoind built with address indexes. Please see the readme file for details.
